### ISSUE TITLE
Undefined offset: 0 in /modules/coinify/coinify.php on line 238

### ISSUE THREAD

**Issue by michaelhjulskov** [CoinifySoftware/prestashop#3]
Hi 
I experience this error in php log file
Here is the code lines :
		function readBitcoinpaymentdetails($id_order)
		{
			$db = Db::getInstance();
			$result = $db->ExecuteS('SELECT * FROM `' . _DB_PREFIX_ . 'order_coinify` WHERE `id_order` = ' . intval($id_order) . ';');
			return (is_array($result[0]))? $result[0] : false;
		}

Should it be:  ?
return (isset($result[0]))? $result[0] : false;

or maybe: ?
return (isset($result[0]) && is_array($result[0]))? $result[0] : false;

Please tell me what to do to get rid of this error

**Comment by koalalorenzo** [comment]
What is exactly the error reporting? Can you write the log here?

**Comment by michaelhjulskov** [comment]
nope i dont have it anymore - its a loooong time ago
